version: '3'
services:
  frontend: # React app with nginx as web server
    image: modernmoodle-frontend
    build: ./frontend/
    networks:
      - dbnetwork
    ports:
      - 8080:80
    depends_on:
      - backend
  backend: # Node.js / Express.js application
    image: modernmoodle-backend
    build: ./backend/
    networks:
      - dbnetwork
      - apinetwork
    ports:
      - 5050:5050
    environment:
      - PG_PORT=5432
      - PG_HOST=database
    depends_on:
      - migration
  database: # Postgres database
    image: postgres:16
    networks:
      - apinetwork
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=modernmoodledb
  migration: # Helper container to create the db schema
    image: modernmoodle-backend
    build: ./backend/
    command: ["npm", "run", "migrate"]
    environment:
      - PG_PORT=5432
      - PG_HOST=database
    depends_on:
      - database
    networks:
      - dbnetwork
networks:
  dbnetwork:
  apinetwork:
    driver: bridge