name: NodeJS backend workflow

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  verify-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: npm ci
    
    - name: Verify eslint rules
      run: npx eslint . --max-warnings 1
    
  verify-lint-for-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: npm ci
    
    - name: Remove **test.ts exclusion
      run: |
        sed '/\*\*\.test\.ts/d' .eslintignore > .eslintignoretmp && mv .eslintignoretmp .eslintignore
        sed '/test\/\*\*\/\*\.ts/d' tsconfig.json > tsconfig.tmp.json && mv tsconfig.tmp.json tsconfig.json

    - name: Verify eslint rules
      run: npx eslint . --max-warnings 1

  build:
    runs-on: ubuntu-latest
    needs: verify-lint

    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build
  
  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run unit-tests
