name: NodeJS backend workflow

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  verify-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: |
        cd backend/
        npm ci
    
    - name: Verify eslint rules
      run: |
        cd backend/
        npx eslint ./src/ --max-warnings 1
    
  verify-lint-for-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: |
        cd backend/
        npm ci

    - name: Verify eslint rules
      run: |
        cd backend/
        npx eslint ./test/ --max-warnings 1

  build:
    runs-on: ubuntu-latest
    needs: verify-lint

    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: |
        cd backend/
        npm ci

    - name: Build project
      run: |
        cd backend/
        npm run build
  
  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: |
        cd backend/
        npm ci
    
    - name: Run unit tests
      run: |
        cd backend/
        npm run unit-tests
  
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Install dependencies
      run: |
        cd backend/
        npm ci

    - name: Run integration tests
      run: |
        cd backend/
        npm run integration-tests
