name: NodeJS with Webpack

on:
  push:
    # TODO: change this back to main
    branches: [ "setup-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm i
        npm run build
