name: NodeJS backend workflow

on:
  push:
    # TODO: change this back to main
    branches: [ "setup-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository
      uses: actions/checkout@v3

    - name: Setup nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.0

    - name: Build
      run: |
        npm i
        npm run build
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Test
      run: echo "Hello, world"
